USE [master]
GO

/****** Object:  Database [CustomerOrdersDB]    Script Date: 2025/06/09 18:13:55 ******/
CREATE DATABASE [CustomerOrdersDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CustomerOrdersDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\CustomerOrdersDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CustomerOrdersDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\CustomerOrdersDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CustomerOrdersDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CustomerOrdersDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CustomerOrdersDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CustomerOrdersDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CustomerOrdersDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CustomerOrdersDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [CustomerOrdersDB] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [CustomerOrdersDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CustomerOrdersDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CustomerOrdersDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CustomerOrdersDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CustomerOrdersDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CustomerOrdersDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CustomerOrdersDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CustomerOrdersDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CustomerOrdersDB] SET  ENABLE_BROKER 
GO

ALTER DATABASE [CustomerOrdersDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CustomerOrdersDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CustomerOrdersDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CustomerOrdersDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CustomerOrdersDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CustomerOrdersDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CustomerOrdersDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CustomerOrdersDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [CustomerOrdersDB] SET  MULTI_USER 
GO

ALTER DATABASE [CustomerOrdersDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CustomerOrdersDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CustomerOrdersDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CustomerOrdersDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CustomerOrdersDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CustomerOrdersDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [CustomerOrdersDB] SET QUERY_STORE = ON
GO

ALTER DATABASE [CustomerOrdersDB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [CustomerOrdersDB] SET  READ_WRITE 
GO

