USE [master]
GO

/****** Object:  Database [DBSocialHire]    Script Date: 2025/06/09 18:15:02 ******/
CREATE DATABASE [DBSocialHire]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DBSocialHire', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\DBSocialHire.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DBSocialHire_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\DBSocialHire_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DBSocialHire].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DBSocialHire] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DBSocialHire] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DBSocialHire] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DBSocialHire] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DBSocialHire] SET ARITHABORT OFF 
GO

ALTER DATABASE [DBSocialHire] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [DBSocialHire] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DBSocialHire] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DBSocialHire] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DBSocialHire] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DBSocialHire] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DBSocialHire] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DBSocialHire] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DBSocialHire] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DBSocialHire] SET  ENABLE_BROKER 
GO

ALTER DATABASE [DBSocialHire] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DBSocialHire] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DBSocialHire] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DBSocialHire] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DBSocialHire] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DBSocialHire] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DBSocialHire] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DBSocialHire] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [DBSocialHire] SET  MULTI_USER 
GO

ALTER DATABASE [DBSocialHire] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DBSocialHire] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DBSocialHire] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DBSocialHire] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DBSocialHire] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DBSocialHire] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [DBSocialHire] SET QUERY_STORE = ON
GO

ALTER DATABASE [DBSocialHire] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [DBSocialHire] SET  READ_WRITE 
GO

