USE [master]
GO

/****** Object:  Database [Parks_and_Recreation]    Script Date: 2025/06/09 18:15:33 ******/
CREATE DATABASE [Parks_and_Recreation]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Parks_and_Recreation', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\Parks_and_Recreation.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Parks_and_Recreation_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\Parks_and_Recreation_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Parks_and_Recreation].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Parks_and_Recreation] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Parks_and_Recreation] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Parks_and_Recreation] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Parks_and_Recreation] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Parks_and_Recreation] SET ARITHABORT OFF 
GO

ALTER DATABASE [Parks_and_Recreation] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [Parks_and_Recreation] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Parks_and_Recreation] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Parks_and_Recreation] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Parks_and_Recreation] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Parks_and_Recreation] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Parks_and_Recreation] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Parks_and_Recreation] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Parks_and_Recreation] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Parks_and_Recreation] SET  ENABLE_BROKER 
GO

ALTER DATABASE [Parks_and_Recreation] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Parks_and_Recreation] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Parks_and_Recreation] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Parks_and_Recreation] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Parks_and_Recreation] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Parks_and_Recreation] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Parks_and_Recreation] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Parks_and_Recreation] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Parks_and_Recreation] SET  MULTI_USER 
GO

ALTER DATABASE [Parks_and_Recreation] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Parks_and_Recreation] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Parks_and_Recreation] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Parks_and_Recreation] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Parks_and_Recreation] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Parks_and_Recreation] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Parks_and_Recreation] SET QUERY_STORE = ON
GO

ALTER DATABASE [Parks_and_Recreation] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [Parks_and_Recreation] SET  READ_WRITE 
GO

