USE [master]
GO

/****** Object:  Database [PLAYETRANSFERE]    Script Date: 2025/06/09 18:16:21 ******/
CREATE DATABASE [PLAYETRANSFERE]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PLAYETRANSFERE', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\PLAYETRANSFERE.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PLAYETRANSFERE_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\PLAYETRANSFERE_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PLAYETRANSFERE].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PLAYETRANSFERE] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PLAYETRANSFERE] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PLAYETRANSFERE] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PLAYETRANSFERE] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PLAYETRANSFERE] SET ARITHABORT OFF 
GO

ALTER DATABASE [PLAYETRANSFERE] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [PLAYETRANSFERE] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PLAYETRANSFERE] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PLAYETRANSFERE] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PLAYETRANSFERE] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PLAYETRANSFERE] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PLAYETRANSFERE] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PLAYETRANSFERE] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PLAYETRANSFERE] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PLAYETRANSFERE] SET  ENABLE_BROKER 
GO

ALTER DATABASE [PLAYETRANSFERE] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PLAYETRANSFERE] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PLAYETRANSFERE] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PLAYETRANSFERE] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PLAYETRANSFERE] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PLAYETRANSFERE] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [PLAYETRANSFERE] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PLAYETRANSFERE] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [PLAYETRANSFERE] SET  MULTI_USER 
GO

ALTER DATABASE [PLAYETRANSFERE] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PLAYETRANSFERE] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PLAYETRANSFERE] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PLAYETRANSFERE] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [PLAYETRANSFERE] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [PLAYETRANSFERE] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [PLAYETRANSFERE] SET QUERY_STORE = ON
GO

ALTER DATABASE [PLAYETRANSFERE] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [PLAYETRANSFERE] SET  READ_WRITE 
GO

