USE [master]
GO

/****** Object:  Database [SampleDbs]    Script Date: 2025/06/09 18:19:58 ******/
CREATE DATABASE [SampleDbs]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SampleDbs', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\SampleDbs.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SampleDbs_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\SampleDbs_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SampleDbs].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SampleDbs] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SampleDbs] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SampleDbs] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SampleDbs] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SampleDbs] SET ARITHABORT OFF 
GO

ALTER DATABASE [SampleDbs] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [SampleDbs] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SampleDbs] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SampleDbs] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SampleDbs] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SampleDbs] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SampleDbs] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SampleDbs] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SampleDbs] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SampleDbs] SET  ENABLE_BROKER 
GO

ALTER DATABASE [SampleDbs] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SampleDbs] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SampleDbs] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SampleDbs] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SampleDbs] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SampleDbs] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SampleDbs] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SampleDbs] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [SampleDbs] SET  MULTI_USER 
GO

ALTER DATABASE [SampleDbs] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SampleDbs] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SampleDbs] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SampleDbs] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [SampleDbs] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SampleDbs] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [SampleDbs] SET QUERY_STORE = ON
GO

ALTER DATABASE [SampleDbs] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [SampleDbs] SET  READ_WRITE 
GO

